name: DRAMMA
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - biopython=1.78=py310h7f8727e_0
  - matplotlib=3.7.0=py310h06a4308_0
  - matplotlib-base=3.7.0=py310h1128e8f_0
  - numpy=1.23.5=py310hd5efca6_0
  - numpy-base=1.23.5=py310h8e6c178_0
  - pandas=1.5.3=py310h1128e8f_0
  - pip=23.0.1=py310h06a4308_0
  - python=3.10.9=h7a1cb2a_1
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python_abi=3.10=2_cp310
  - requests=2.28.1=py310h06a4308_0
  - scikit-learn=1.2.0=py310h6a678d5_0
  - scipy=1.10.0=py310hd5efca6_1
  - seaborn=0.12.2=py310h06a4308_0
  - urllib3=1.26.14=py310h06a4308_0
  - pip:
      - mpmath==1.3.0
